### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by qiangrw**
add qianyu's home folder

### CODE REVIEW

**Comment by Bankq** [comment]
@qdx nexttime you merge dev to master, remember to clean the history using `git rebase`. Only meaningful commits should appear in the master history. I'll let your ass not kicked this time.

**Comment by qdx** [comment]
我怕rebase给大家造成不便……
在 2012/10/18 11:37 AM，"Bank Qian" notifications@github.com写道：

**Comment by Bankq** [comment]
你只需要rebase你自己的commit就行了，这是在你merge到dev分支之前做的事情。

On Thu, Oct 18, 2012 at 2:39 PM, qdx notifications@github.com wrote:

> 我怕rebase给大家造成不便……
> 在 2012/10/18 11:37 AM，"Bank Qian" notifications@github.com写道：
> 
> > @qdx https://github.com/qdx nexttime you merge dev to master,
> > remember
> > to clean the history using git rebase. Only meaningful commits should
> > appear in the master history. I'll let your ass not kicked this time.
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/localsnake/localsnake.org/pull/11#issuecomment-9576709>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/localsnake/localsnake.org/pull/11#issuecomment-9576805.

## 

Best regards,
   Hang Qian

**Comment by qdx** [comment]
这个我做了呀……
在 2012/10/18 11:56 AM，"Bank Qian" notifications@github.com写道：

> 你只需要rebase你自己的commit就行了，这是在你merge到dev分支之前做的事情。
>

**Comment by Bankq** [comment]
rebase完了还那么多commit??

On Thu, Oct 18, 2012 at 2:57 PM, qdx notifications@github.com wrote:

> 这个我做了呀……
> 在 2012/10/18 11:56 AM，"Bank Qian" notifications@github.com写道：
> 
> > 你只需要rebase你自己的commit就行了，这是在你merge到dev分支之前做的事情。
> > 
> > On Thu, Oct 18, 2012 at 2:39 PM, qdx notifications@github.com wrote:
> > 
> > > 我怕rebase给大家造成不便……
> > > 在 2012/10/18 11:37 AM，"Bank Qian" notifications@github.com写道：
> > > 
> > > > @qdx https://github.com/qdx nexttime you merge dev to master,
> > > > remember
> > > > to clean the history using git rebase. Only meaningful commits
> > > > should
> > > > appear in the master history. I'll let your ass not kicked this
> > > > time.
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > 
> > https://github.com/localsnake/localsnake.org/pull/11#issuecomment-9576709>.
> > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > 
> > https://github.com/localsnake/localsnake.org/pull/11#issuecomment-9576805>.
> > 
> > 
> > ## 
> > 
> > Best regards,
> > Hang Qian
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/localsnake/localsnake.org/pull/11#issuecomment-9577841>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/localsnake/localsnake.org/pull/11#issuecomment-9577905.

## 

Best regards,
   Hang Qian

**Comment by qdx** [comment]
我在自己的上面rebase了merge过来以后这些东西又出来了……我是得直接把rebase好的push到localsnake这边才行吗？
在 2012/10/18 11:59 AM，"Bank Qian" notifications@github.com写道：

> rebase完了还那么多commit??
>

**Comment by Bankq** [comment]
没听懂…………
你rebase之后应该历史就消失了啊？

没事，我最近在考虑正式开始运营localsnake.org了，这个周么会写封邮件给你们。

On Thu, Oct 18, 2012 at 3:04 PM, qdx notifications@github.com wrote:

> 我在自己的上面rebase了merge过来以后这些东西又出来了……我是得直接把rebase好的push到localsnake这边才行吗？
> 在 2012/10/18 11:59 AM，"Bank Qian" notifications@github.com写道：
> 
> > rebase完了还那么多commit??
> > 
> > On Thu, Oct 18, 2012 at 2:57 PM, qdx notifications@github.com wrote:
> > 
> > > 这个我做了呀……
> > > 在 2012/10/18 11:56 AM，"Bank Qian" notifications@github.com写道：
> > > 
> > > > 你只需要rebase你自己的commit就行了，这是在你merge到dev分支之前做的事情。
> > > > 
> > > > On Thu, Oct 18, 2012 at 2:39 PM, qdx notifications@github.com
> > > > wrote:
> > > > 
> > > > > 我怕rebase给大家造成不便……
> > > > > 在 2012/10/18 11:37 AM，"Bank Qian" notifications@github.com写道：
> > > > > 
> > > > > > @qdx https://github.com/qdx nexttime you merge dev to master,
> > > > > > remember
> > > > > > to clean the history using git rebase. Only meaningful commits
> > > > > > should
> > > > > > appear in the master history. I'll let your ass not kicked this
> > > > > > time.
> > > > > > 
> > > > > > —
> > > > > > Reply to this email directly or view it on GitHub<
> > 
> > https://github.com/localsnake/localsnake.org/pull/11#issuecomment-9576709>.
> > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub<
> > 
> > https://github.com/localsnake/localsnake.org/pull/11#issuecomment-9576805>.
> > 
> > > > ## 
> > > > 
> > > > Best regards,
> > > > Hang Qian
> > > > 
> > > > —
> > > > Reply to this email directly or view it on GitHub<
> > 
> > https://github.com/localsnake/localsnake.org/pull/11#issuecomment-9577841>.
> > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > 
> > https://github.com/localsnake/localsnake.org/pull/11#issuecomment-9577905>.
> > 
> > 
> > ## 
> > 
> > Best regards,
> > Hang Qian
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/localsnake/localsnake.org/pull/11#issuecomment-9577951>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/localsnake/localsnake.org/pull/11#issuecomment-9578122.

## 

Best regards,
   Hang Qian

**Comment by qdx** [comment]
Ok~我抽空再去修理一下历史
在 2012/10/18 12:06 PM，"Bank Qian" notifications@github.com写道：

> 没听懂…………
> 你rebase之后应该历史就消失了啊？
> 
> 没事，我最近在考虑正式开始运营localsnake.org了，这个周么会写封邮件给你们。
>

**Comment by qdx** [comment]
清理了commit历史，不过由于原先的历史太乱了……于是清理完之后，我手动重新添加了qianyu的folder并且commit了，于是qianyu本来的commit就丢了……实乃我二逼，情各位见谅……

**Comment by qiany** [comment]
Yu Qian

From: qdx
Date: 2012-10-19 12:17
To: localsnake/localsnake.org
Subject: Re: [localsnake.org] Dev (#11)
清理了commit历史，不过由于原先的历史太乱了……于是清理完之后，我手动重新添加了qianyu的folder并且commit了，于是qianyu本来的commit就丢了……实乃我二逼，情各位见谅……

**Comment by qdx** [comment]
瘪瘪……我错了……

2012/10/18 Yu Qian notifications@github.com

> Yu Qian
> 
> From: qdx
> Date: 2012-10-19 12:17
> To: localsnake/localsnake.org
> Subject: Re: [localsnake.org] Dev (#11)
> 清理了commit历史，不过由于原先的历史太乱了……于是清理完之后，我手动重新添加了qianyu的folder并且commit了，于是qianyu本来的commit就丢了……实乃我二逼，情各位见谅……
>

**Pull request merged**
